# Generated by Django 4.2.5 on 2025-09-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_data_evento_data_inicio_evento_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome do Campo (ex: nome_completo)')),
                ('label_campo', models.CharField(max_length=100, verbose_name='Rótulo (ex: Nome Completo)')),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto Curto'), ('textarea', 'Texto Longo'), ('radio', 'Opção de Escolha Única'), ('number', 'Número'), ('email', 'E-mail'), ('tel', 'Telefone'), ('checkbox', 'Caixa de Seleção')], max_length=10)),
                ('is_required', models.BooleanField(default=True, verbose_name='É obrigatório?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Campo Ativo')),
                ('opcoes', models.TextField(blank=True, help_text='Separe as opções com vírgula (ex: Sim, Não). Apenas para campos de rádio.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Evento Ativo'),
        ),
        migrations.CreateModel(
            name='RespostaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(verbose_name='Valor da Resposta')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.campoformulario')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='eventos.participanteevento')),
            ],
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.evento'),
        ),
        migrations.CreateModel(
            name='EventoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='eventos_midia/', verbose_name='Arquivo de Mídia')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=10, verbose_name='Tipo de Mídia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Mídia do Evento',
                'verbose_name_plural': 'Mídias dos Eventos',
            },
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_formulario', to='eventos.evento'),
        ),
    ]
