# Generated by Django 4.2.5 on 2025-09-22 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_campoformulario_participanteevento_evento_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='eventomidia',
            options={},
        ),
        migrations.RenameField(
            model_name='eventomidia',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='participanteevento',
            old_name='data_inscricao',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='campoformulario',
            name='label_campo',
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='nome_campo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='opcoes',
            field=models.CharField(blank=True, help_text='Para campos de rádio, separe as opções por vírgula. Ex: Sim,Não', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='tipo_campo',
            field=models.CharField(choices=[('texto', 'Texto Curto'), ('multitexto', 'Texto Longo'), ('numero', 'Número'), ('email', 'Email'), ('radio', 'Opções de Rádio'), ('checkbox', 'Caixa de Seleção')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default='Sem descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventomidia',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventomidia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='eventomidia',
            name='media_file',
            field=models.FileField(upload_to='evento_midias/'),
        ),
        migrations.AlterField(
            model_name='eventomidia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='respostacampo',
            name='valor',
            field=models.TextField(),
        ),
    ]
