# Generated by Django 4.2.5 on 2025-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_campoformulario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='status_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='trabalha_no_evento',
            field=models.BooleanField(default=False),
        ),
    ]
