# Generated by Django 4.2.5 on 2025-09-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_participanteevento_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacampo',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
