# Generated by Django 4.2.5 on 2025-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_respostacampo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='pagamento_recebido',
            field=models.BooleanField(default=False),
        ),
    ]
