# Generated by Django 4.2.5 on 2025-09-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_participanteevento_pagamento_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
