# Generated by Django 4.2.5 on 2025-11-17 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0008_evento_qrcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='mp_receiver_id',
            field=models.CharField(blank=True, help_text='ID da conta do Mercado Pago (user_id) do criador para receber os pagamentos.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, default='evento-antigo', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
