# Generated by Django 4.2.5 on 2025-09-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0008_evento_qrcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterField(
            model_name="evento",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
