# Generated by Django 4.2.5 on 2026-05-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_alter_evento_options_alter_evento_slug"),
        ("eventos", "0009_alter_evento_options_evento_criador_and_more"),
    ]

    operations = []
