# Generated by Django 4.2.5 on 2026-08-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0010_merge_20260519_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_eventos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastrado'),
        ),
    ]
