# Generated by Django 4.2.5 on 2025-09-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncontroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='encontro_media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mídia do Encontro',
                'verbose_name_plural': 'Mídias do Encontro',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('nome_lider', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_amigo_familiar', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_amigo_familiar', models.CharField(blank=True, max_length=20, null=True)),
                ('expectativas', models.TextField(blank=True, null=True)),
                ('evento_pago', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('trabalho_encontro', models.BooleanField(default=False, verbose_name='Vou trabalhar no Encontro')),
            ],
        ),
    ]
