# Generated by Django 4.2.5 on 2025-08-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0002_participante_evento_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncontroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='encontro_fotos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do Encontro',
                'verbose_name_plural': 'Imagens do Encontro',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
