# Generated by Django 4.2.5 on 2025-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0003_encontroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='trabalho_encontro',
            field=models.BooleanField(default=False, verbose_name='Vou trabalhar no Encontro'),
        ),
    ]
