# Generated by Django 4.2.5 on 2025-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0004_participante_trabalho_encontro'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificacaoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_encontro', models.IntegerField(verbose_name='Número Ordinal do Encontro')),
                ('sexo', models.CharField(choices=[('H', 'Homens'), ('M', 'Mulheres')], max_length=1)),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativar')),
            ],
        ),
    ]
