# Generated by Django 4.2.5 on 2025-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0005_identificacaoencontro'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='genero_encontro',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='participante',
            name='ordem_encontro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Encontro com Deus'),
        ),
    ]
