# Generated by Django 4.2.5 on 2025-08-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0006_participante_genero_encontro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificacaoencontro',
            options={'verbose_name': 'Identificação do Encontro', 'verbose_name_plural': 'Identificação dos Encontros'},
        ),
        migrations.AddField(
            model_name='identificacaoencontro',
            name='data_fim',
            field=models.DateField(default='2025-10-17', verbose_name='Data de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificacaoencontro',
            name='data_inicio',
            field=models.DateField(default='2025-10-15', verbose_name='Data de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificacaoencontro',
            name='valor_encontro',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=8, verbose_name='Valor do Encontro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='ordem_encontro',
            field=models.PositiveIntegerField(unique=True, verbose_name='Ordem do Encontro'),
        ),
    ]
