# Generated by Django 4.2.5 on 2025-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0007_alter_identificacaoencontro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacaoencontro',
            name='nome_do_evento',
            field=models.CharField(default='Encontro com Deus', max_length=100, verbose_name='Nome do Evento'),
        ),
    ]
