# Generated by Django 4.2.5 on 2025-08-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0008_identificacaoencontro_nome_do_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encontroimage',
            options={'verbose_name': 'Imagem do Encontro', 'verbose_name_plural': 'Imagens do Encontro'},
        ),
        migrations.AlterModelOptions(
            name='identificacaoencontro',
            options={'verbose_name': 'Identificação do Encontro', 'verbose_name_plural': 'Identificações dos Encontros'},
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='image',
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='encontro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='encontro_com_deus.identificacaoencontro', verbose_name='Encontro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='genero_encontro',
            field=models.CharField(blank=True, choices=[('H', 'Homens'), ('M', 'Mulheres')], max_length=1, null=True, verbose_name='Gênero do Encontro'),
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='imagem',
            field=models.ImageField(default=1, upload_to='encontro_images/', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='ordem_encontro',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° do Encontro'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='data_fim',
            field=models.DateField(verbose_name='Data do Fim'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Encontro Ativo'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='ordem_encontro',
            field=models.IntegerField(unique=True, verbose_name='N° do Encontro'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='sexo',
            field=models.CharField(choices=[('H', 'Homens'), ('M', 'Mulheres')], max_length=1, verbose_name='Gênero do Encontro'),
        ),
        migrations.AlterField(
            model_name='identificacaoencontro',
            name='valor_encontro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Encontro'),
        ),
    ]
