# Generated by Django 4.2.5 on 2025-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0009_alter_encontroimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='nome_do_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Evento'),
        ),
    ]
