# Generated by Django 4.2.5 on 2025-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0010_participante_nome_do_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encontroimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Imagem do Encontro', 'verbose_name_plural': 'Imagens do Encontro'},
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='encontro',
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='genero_encontro',
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='ordem_encontro',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='genero_encontro',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='nome_do_evento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='ordem_encontro',
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='image',
            field=models.ImageField(default='', upload_to='encontro_fotos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IdentificacaoEncontro',
        ),
    ]
