# Generated by Django 4.2.5 on 2025-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontro_com_deus', '0011_alter_encontroimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encontroimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Mídia do Encontro', 'verbose_name_plural': 'Mídias do Encontro'},
        ),
        migrations.RemoveField(
            model_name='encontroimage',
            name='image',
        ),
        migrations.AddField(
            model_name='encontroimage',
            name='media',
            field=models.FileField(default='', upload_to='encontro_media/'),
            preserve_default=False,
        ),
    ]
