# Generated by Django 4.2.5 on 2025-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago User ID'),
        ),
    ]
