# Generated by Django 4.2.5 on 2026-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_mp_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Access Token'),
        ),
    ]
