# Generated by Django 4.2.5 on 2025-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título (Opcional)')),
                ('image', models.ImageField(upload_to='carousel_images/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa no Carrossel?')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
